version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/application
    volumes:
      - ./:/var/www/application
    networks:
      - laravel_network

  nginx-proxy:
    image: nginx:alpine
    container_name: common-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/application
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - app

  mysql8:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - mysql8:db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel_network
    depends_on:
      - mysql8
      - nginx-proxy

volumes:
  mysql_data:
 
networks:
  laravel_network:
    driver: bridge
